title: Dat 1. semester
remote_theme: just-the-docs/just-the-docs
description: >- # this means to ignore newlines until "baseurl:"
  Selve afviklingen af 1. semester foregår via Moodle. Dvs, at man på Moodle kan se tid/sted for undervisningen og hvad der arbejdes med hvornår. 
  Det meste af indholdet ligger her på GitHub. Det har vi valgt at gøre fordi mange af materialerne indholder kodestumper, som GitHub kan gengive med fremhævning af syntaks og mulighed for at kopiere indholdet. 
  Det sparer os alle for meget tid og besvær.
url:  https://dat1cphbusiness.github.io # the base hostname & protocol for your site, e.g. http://example.com
logo: '/assets/images/cphbusiness.png'
favicon_ico: '/assets/images/favicon.ico'
aux_links:
  Repository: https://github.com/Dat1Cphbusiness/content
  Moodlerum: https://cphbusiness.mrooms.net/course/view.php?id=15022
  Slides: https://efif.sharepoint.com/:f:/r/sites/cph/Lyngby/Shared%20Documents/4.%20Indhold%20%26%20Niveau/DAT/1.sem%20for%C3%A5r%202025/studerende/slides?csf=1&web=1&e=sKSoGP

nav_enabled: true
heading_anchors: true
search_enabled: true

# Build settings

plugins:
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-sitemap

readme_index:
  enabled: true
  remove_originals: true
  with_frontmatter: false
  # Color scheme supports "light" (default) and "dark"
  color_scheme: light

  # Back to top link
  back_to_top: true
  back_to_top_text: 'Top'

  # For copy button on code
  enable_copy_code_button: true

  footer_content: '1. semester forår 2025'
  last_edit_timestamp: true

  # Makes Aux links open in a new tab. Default is false
  aux_links_new_tab: true

  exclude:
    # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    # specific to the theme website:
    - bin/
    - lib/
    - '*.gemspec'
    - '*.gem'
    - LICENSE.txt
    - package.json
    - package-lock.json
    - Rakefile
    - CODE_OF_CONDUCT.md
    - docker-compose.yml
    - Dockerfile
    # theme test code
    - fixtures/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
